import { requireNativeModule } from 'expo-modules-core';

/**
 * TypeScrip Interference
 * This 'NativeDicom' object is automatically generated by Expo Modules Core.
 * It links this TypeScript file to the 'NativeDicomModule.kt' class in Android.
 */
const NativeDicom = requireNativeModule('NativeDicom');

/**
 * JSI Interface
 * This is the high-performance interface for DICOM parsing.
 */
export interface DicomParserJSI {
  getMetaData(): DicomMetaData;
  getFramePixels(frameIndex: number): Uint8Array | null;
}

declare global {
  var NativeDicomJSI: {
    createParserJSI(path: string): DicomParserJSI | null;
  } | undefined;
}

/**
 * Creates a new DicomParser instance using JSI.
 * @returns A DicomParserJSI object or null if failed.
 */
export function createParserJSI(filePath: string): DicomParserJSI | null {
  if (typeof global.NativeDicomJSI === 'undefined') {
    console.error("NativeDicomJSI is not installed. Ensure the module is properly loaded.");
    return null;
  }
  return global.NativeDicomJSI.createParserJSI(filePath);
}

export interface DicomMetaData {
  width: number;
  height: number;
  numFrames: number;
  bitsAllocated: number;
  bitsStored: number;
  pixelRepresentation: number;
  photometricInterpretation: string;
}

/**
 * Creates a new DicomParser instance for the given file path.
 * FLOW: TS Function -> Expo Module (Kotlin) -> JNI (C++) -> DicomParser (C++)
 * @returns An instance ID if successful, or null.
 */
export function createParser(filePath: string): string | null {
  // This calls the 'Function("createParser")' defined in NativeDicomModule.kt
  return NativeDicom.createParser(filePath);
}

/**
 * Retrieves metadata for the given parser instance.
 */
export function getMetaData(instanceId: string): DicomMetaData | null {
  return NativeDicom.getMetaData(instanceId);
}

/**
 * Retrieves pixel data for a specific frame.
 * @returns A Uint8Array containing the raw pixel data.
 */
export function getFramePixels(instanceId: string, frameIndex: number): Uint8Array | null {
  return NativeDicom.getFramePixels(instanceId, frameIndex);
}

/**
 * Releases the native parser instance and frees associated memory.
 */
export function releaseParser(instanceId: string): void {
  NativeDicom.releaseParser(instanceId);
}
